In [1]:
import numpy as np
import matplotlib.pyplot as plt

Recall how to create a numpy array

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Indexing and slicing of numpy array. `a[-1]` accesses the last element in the array.
Remember that the end index in a slice `a[1,3]` is always *exclusive*, so `a[3]` is not part of the slice.

In [3]:
print(a[0])
print(a[-1])
print(a[1:3])
print(a[1:-1])

1
5
[2 3]
[2 3 4]


## Composite trapezoidal rule
Using the trapezoidal rule

$\mathrm{T}[f](x_{i-1},x_{i})
=
\tfrac{h}{2} f(x_{i-1}) + \tfrac{h}{2} f(x_{i})
$
the resulting composite trapezoidal rule is given by

$$
\begin{align*}
\int_a^b f {\,\mathrm{d}x} \approx \mathrm{CT}[f]({[x_{i-1}, x_{i}]}_{i=1}^{m})
= h \left[ \tfrac{1}{2} f(x_0) + f(x_1) + \ldots + f(x_{m-1}) + \tfrac{1}{2} f(x_m) \right]
\end{align*}
$$

In [5]:
def f(x):
    return np.sin(x)

In [11]:
m = 2
a, b = 0 ,1 
h = (b-a)/m
x = np.linspace(a, b, m+1)
fx = f(x)
print(fx)
fxinner =  f(x[1:-1])
print(fxinner)
sum = np.sum(fxinner)
sum += 0.5*fx[0]
sum += 0.5*fx[-1]
sum *= h
print(sum)
print(f"x = {x}")
xm = np.linspace(a+h/2,b-h/2,m)
print(f" xm = {xm}")
fxm = f(xm)
sum_xm = h/6*4*np.sum(fxm)
csr = sum + sum_xm

[0.         0.47942554 0.84147098]
[0.47942554]
0.45008051550407563
x = [0.  0.5 1. ]
 xm = [0.25 0.75]


Now we wrap the code above into a little function, which takes the interval endpoints $a,b$ and the number of subintervals as function arguments
and which returns the computed integral approximation.

**N.B.** There was two bugs in my implementation during the tutorial since I copied/pasted the two snippets using
`fx[0]` and `fx[-1]` into the function instead of using `f(x[0])` and `f(x[-1])`. The code worked nevertheless
since we had already defined it earlier, so we first discovered the bugs when we copied this over to another notebook.
The code below for CTR and CSR is now correct.


In [12]:
def CTR(f, a, b, m):
    h = (b-a)/m
    x = np.linspace(a,b,m+1)
    sum = np.sum(f(x[1:-1]))
    sum += 0.5*f(x[0]) # Bug: I wrote fx[0] during the tutorial
    sum += 0.5*f(x[-1]) # Bug: I wrote fx[-1] during the tutorial
    sum *= h
    
    return sum

In [9]:
ctr = CTR(f, a, b, m)
print(ctr)

0.45008051550407563


Implement the composite Simpson's rule which is given by

\begin{align*}
\int_a^b f {\,\mathrm{d}x} \approx \mathrm{CSR}[f]({[x_{i-1}, x_i]}_{i=1}^{m})
&= 
\tfrac{h}{6}
[
f(x_0)
+ 4f(x_{x_{1/2}}) + 2f(x_1) 
+ 4f(x_{3/2}) +     2f(x_2)
+ \ldots
\\ 
&\qquad+2 f(x_{m-1})
+
4f(x_{x_{m-1/2}}) 
+f(x_m)
].
\end{align*}

In [14]:
def CSR(f, a, b, m):
    h = (b-a)/m
    # Glem delintervalmidpunktene først
    x = np.linspace(a,b,m+1)
    sum = 2*np.sum(f(x[1:-1]))
    sum += f(x[0])
    sum += f(x[-1])
    sum *= h/6
    
    # Beregn og legg til bidragene fra delintervalsmidpunktene
    xm = np.linspace(a+h/2, b-h/2, m)
    sum += h/6*4*np.sum(f(xm))
    return sum